from django.urls import path
from .views import (
    index,
    login_view,
    logout_view,
    home_view,
    usuarios_listar,
    usuarios_crear,
    usuarios_editar,
    usuarios_eliminar,
    canciones_listar,
    canciones_like,
    canciones_quitar_like,
    albumes_listar,
    likes_listar,
    playlists_listar,
    playlists_crear,
    playlists_detalle,
    playlists_agregar_cancion,
    playlists_quitar_cancion,
    artistas_listar,
    artistas_crear,
    artistas_editar,
    artistas_eliminar,
    albumes_admin,
    canciones_admin,
    reportes
)
urlpatterns = [
    path('', index, name='index'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('home/', home_view, name='home'),

    path('usuarios/', usuarios_listar, name='usuarios_listar'),
    path('usuarios/crear/', usuarios_crear, name='usuarios_crear'),
    path('usuarios/editar/<int:idUsuario>/', usuarios_editar, name='usuarios_editar'),
    path('usuarios/eliminar/<int:idUsuario>/', usuarios_eliminar, name='usuarios_eliminar'),
    path('canciones/', canciones_listar, name='canciones_listar'),
    path('canciones/like/<int:idCancion>/', canciones_like, name='canciones_like'),
    path('canciones/quitar-like/<int:idCancion>/', canciones_quitar_like, name='canciones_quitar_like'),
    path('albumes/', albumes_listar, name='albumes_listar'),
    path('mis-likes/', likes_listar, name='likes_listar'),
    path('playlists/', playlists_listar, name='playlists_listar'),
    path('playlists/crear/', playlists_crear, name='playlists_crear'),
    path('playlists/<int:idPlaylist>/', playlists_detalle, name='playlists_detalle'),
    path('playlists/<int:idPlaylist>/agregar-cancion/', playlists_agregar_cancion, name='playlists_agregar_cancion'),
    path('playlists/<int:idPlaylist>/quitar-cancion/<int:idCancion>/', playlists_quitar_cancion, name='playlists_quitar_cancion'),
    path('artistas/', artistas_listar, name='artistas_listar'),
    path('artistas/crear/', artistas_crear, name='artistas_crear'),
    path('artistas/editar/<int:idArtista>/', artistas_editar, name='artistas_editar'),
    path('artistas/eliminar/<int:idArtista>/', artistas_eliminar, name='artistas_eliminar'),
    path('albumes-admin/', albumes_admin, name='albumes_admin'),
    path('canciones-admin/', canciones_admin, name='canciones_admin'),
    path('reportes/', reportes, name='reportes'),
]
