USE StreamFlowDB;
GO

DECLARE @idDiscograficaPopular INT;

IF NOT EXISTS (
    SELECT 1
    FROM Catalogo.Discografia
    WHERE nombreDisquera = 'StreamFlow Global'
)
BEGIN
    INSERT INTO Catalogo.Discografia (nombreDisquera, paisDisquera)
    VALUES ('StreamFlow Global', 'Estados Unidos');
END

SELECT @idDiscograficaPopular = idDiscografica
FROM Catalogo.Discografia
WHERE nombreDisquera = 'StreamFlow Global';

DECLARE @Popular TABLE (
    artista NVARCHAR(120),
    pais NVARCHAR(80),
    album NVARCHAR(160),
    tipo NVARCHAR(40),
    titulo NVARCHAR(180),
    duracionSeg INT
);

INSERT INTO @Popular (artista, pais, album, tipo, titulo, duracionSeg)
VALUES
(N'Drake', N'Estados Unidos', N'Drake Essentials', N'Coleccion', N'God''s Plan', 198),
(N'Drake', N'Estados Unidos', N'Drake Essentials', N'Coleccion', N'One Dance', 174),
(N'Drake', N'Estados Unidos', N'Drake Essentials', N'Coleccion', N'Hotline Bling', 267),
(N'Drake', N'Estados Unidos', N'Drake Essentials', N'Coleccion', N'In My Feelings', 217),
(N'Drake', N'Estados Unidos', N'Drake Essentials', N'Coleccion', N'Passionfruit', 299),
(N'Bad Bunny', N'Puerto Rico', N'Bad Bunny Essentials', N'Coleccion', N'Tití Me Preguntó', 244),
(N'Bad Bunny', N'Puerto Rico', N'Bad Bunny Essentials', N'Coleccion', N'Moscow Mule', 245),
(N'Bad Bunny', N'Puerto Rico', N'Bad Bunny Essentials', N'Coleccion', N'Dakiti', 205),
(N'Bad Bunny', N'Puerto Rico', N'Bad Bunny Essentials', N'Coleccion', N'Me Porto Bonito', 179),
(N'Bad Bunny', N'Puerto Rico', N'Bad Bunny Essentials', N'Coleccion', N'Yonaguni', 206),
(N'Rauw Alejandro', N'Puerto Rico', N'Rauw Alejandro Essentials', N'Coleccion', N'Todo de Ti', 199),
(N'Rauw Alejandro', N'Puerto Rico', N'Rauw Alejandro Essentials', N'Coleccion', N'Desesperados', 224),
(N'Rauw Alejandro', N'Puerto Rico', N'Rauw Alejandro Essentials', N'Coleccion', N'Dile a Él', 205),
(N'Rauw Alejandro', N'Puerto Rico', N'Rauw Alejandro Essentials', N'Coleccion', N'Museo', 208),
(N'Rauw Alejandro', N'Puerto Rico', N'Rauw Alejandro Essentials', N'Coleccion', N'Punto 40', 190),
(N'Mora', N'Puerto Rico', N'Mora Essentials', N'Coleccion', N'La Inocente', 203),
(N'Mora', N'Puerto Rico', N'Mora Essentials', N'Coleccion', N'Memoria', 186),
(N'Mora', N'Puerto Rico', N'Mora Essentials', N'Coleccion', N'Domingo de Bote', 192),
(N'Mora', N'Puerto Rico', N'Mora Essentials', N'Coleccion', N'Aurora', 201),
(N'Mora', N'Puerto Rico', N'Mora Essentials', N'Coleccion', N'Volando', 213),
(N'Paulo Londra', N'Argentina', N'Paulo Londra Essentials', N'Coleccion', N'Adán y Eva', 258),
(N'Paulo Londra', N'Argentina', N'Paulo Londra Essentials', N'Coleccion', N'Tal Vez', 244),
(N'Paulo Londra', N'Argentina', N'Paulo Londra Essentials', N'Coleccion', N'Nena Maldición', 227),
(N'Paulo Londra', N'Argentina', N'Paulo Londra Essentials', N'Coleccion', N'Plan A', 178),
(N'Paulo Londra', N'Argentina', N'Paulo Londra Essentials', N'Coleccion', N'Forever Alone', 220),
(N'Bizarrap', N'Argentina', N'Bizarrap Sessions', N'Coleccion', N'BZRP Music Sessions Vol. 52', 198),
(N'Bizarrap', N'Argentina', N'Bizarrap Sessions', N'Coleccion', N'BZRP Music Sessions Vol. 53', 218),
(N'Bizarrap', N'Argentina', N'Bizarrap Sessions', N'Coleccion', N'BZRP Music Sessions Vol. 36', 160),
(N'Bizarrap', N'Argentina', N'Bizarrap Sessions', N'Coleccion', N'BZRP Music Sessions Vol. 49', 178),
(N'Bizarrap', N'Argentina', N'Bizarrap Sessions', N'Coleccion', N'BZRP Music Sessions Vol. 57', 172),
(N'Nicki Nicole', N'Argentina', N'Nicki Nicole Essentials', N'Coleccion', N'Wapo Traketero', 187),
(N'Nicki Nicole', N'Argentina', N'Nicki Nicole Essentials', N'Coleccion', N'Colocao', 185),
(N'Nicki Nicole', N'Argentina', N'Nicki Nicole Essentials', N'Coleccion', N'Mala Vida', 196),
(N'Nicki Nicole', N'Argentina', N'Nicki Nicole Essentials', N'Coleccion', N'Dispara', 174),
(N'Nicki Nicole', N'Argentina', N'Nicki Nicole Essentials', N'Coleccion', N'Ojos Verdes', 210),
(N'Rels B', N'España', N'Rels B Essentials', N'Coleccion', N'A Mí', 186),
(N'Rels B', N'España', N'Rels B Essentials', N'Coleccion', N'cómo dormiste?', 121),
(N'Rels B', N'España', N'Rels B Essentials', N'Coleccion', N'lo que hay x aquí', 180),
(N'Rels B', N'España', N'Rels B Essentials', N'Coleccion', N'Buenos Genes', 194),
(N'Rels B', N'España', N'Rels B Essentials', N'Coleccion', N'Me Olvidé de los 2', 206),
(N'Yandel', N'Puerto Rico', N'Yandel Essentials', N'Coleccion', N'Encantadora', 223),
(N'Yandel', N'Puerto Rico', N'Yandel Essentials', N'Coleccion', N'Nunca Me Olvides', 216),
(N'Yandel', N'Puerto Rico', N'Yandel Essentials', N'Coleccion', N'Explícale', 221),
(N'Yandel', N'Puerto Rico', N'Yandel Essentials', N'Coleccion', N'Yandel 150', 216),
(N'Yandel', N'Puerto Rico', N'Yandel Essentials', N'Coleccion', N'Solo Mía', 204),
(N'Latin Mafia', N'México', N'Latin Mafia Essentials', N'Coleccion', N'Patadas de Ahogado', 192),
(N'Latin Mafia', N'México', N'Latin Mafia Essentials', N'Coleccion', N'Se Fue la Luz', 183),
(N'Latin Mafia', N'México', N'Latin Mafia Essentials', N'Coleccion', N'Julieta', 176),
(N'Latin Mafia', N'México', N'Latin Mafia Essentials', N'Coleccion', N'Continuo Atardecer', 202),
(N'Latin Mafia', N'México', N'Latin Mafia Essentials', N'Coleccion', N'Flores', 195),
(N'HUMBE', N'México', N'HUMBE Essentials', N'Coleccion', N'Fantasmas', 223),
(N'HUMBE', N'México', N'HUMBE Essentials', N'Coleccion', N'Confieso', 203),
(N'HUMBE', N'México', N'HUMBE Essentials', N'Coleccion', N'El Poeta', 214),
(N'HUMBE', N'México', N'HUMBE Essentials', N'Coleccion', N'Amor de Cine', 210),
(N'HUMBE', N'México', N'HUMBE Essentials', N'Coleccion', N'Kintsugi', 196),
(N'Nilo J', N'Argentina', N'Nilo J Essentials', N'Coleccion', N'Milo J BZRP Music Sessions Vol. 57', 172),
(N'Nilo J', N'Argentina', N'Nilo J Essentials', N'Coleccion', N'Milagrosa', 192),
(N'Nilo J', N'Argentina', N'Nilo J Essentials', N'Coleccion', N'Rara Vez', 188),
(N'Nilo J', N'Argentina', N'Nilo J Essentials', N'Coleccion', N'M.A.I', 190),
(N'Nilo J', N'Argentina', N'Nilo J Essentials', N'Coleccion', N'Al Borde', 199),
(N'Kendrick Lamar', N'Estados Unidos', N'Hip Hop US Essentials', N'Coleccion', N'HUMBLE.', 177),
(N'Kendrick Lamar', N'Estados Unidos', N'Hip Hop US Essentials', N'Coleccion', N'DNA.', 185),
(N'Kendrick Lamar', N'Estados Unidos', N'Hip Hop US Essentials', N'Coleccion', N'Not Like Us', 274),
(N'Kendrick Lamar', N'Estados Unidos', N'Hip Hop US Essentials', N'Coleccion', N'Swimming Pools', 247),
(N'Kendrick Lamar', N'Estados Unidos', N'Hip Hop US Essentials', N'Coleccion', N'All The Stars', 232),
(N'Travis Scott', N'Estados Unidos', N'Travis Scott Essentials', N'Coleccion', N'SICKO MODE', 312),
(N'Travis Scott', N'Estados Unidos', N'Travis Scott Essentials', N'Coleccion', N'goosebumps', 243),
(N'Travis Scott', N'Estados Unidos', N'Travis Scott Essentials', N'Coleccion', N'HIGHEST IN THE ROOM', 175),
(N'Travis Scott', N'Estados Unidos', N'Travis Scott Essentials', N'Coleccion', N'FE!N', 191),
(N'Travis Scott', N'Estados Unidos', N'Travis Scott Essentials', N'Coleccion', N'MY EYES', 251),
(N'Post Malone', N'Estados Unidos', N'Post Malone Essentials', N'Coleccion', N'Circles', 215),
(N'Post Malone', N'Estados Unidos', N'Post Malone Essentials', N'Coleccion', N'Sunflower', 158),
(N'Post Malone', N'Estados Unidos', N'Post Malone Essentials', N'Coleccion', N'Rockstar', 218),
(N'Post Malone', N'Estados Unidos', N'Post Malone Essentials', N'Coleccion', N'Congratulations', 220),
(N'Post Malone', N'Estados Unidos', N'Post Malone Essentials', N'Coleccion', N'I Had Some Help', 178),
(N'The Weeknd', N'Canadá', N'The Weeknd Essentials', N'Coleccion', N'Blinding Lights', 200),
(N'The Weeknd', N'Canadá', N'The Weeknd Essentials', N'Coleccion', N'Starboy', 230),
(N'The Weeknd', N'Canadá', N'The Weeknd Essentials', N'Coleccion', N'Save Your Tears', 215),
(N'The Weeknd', N'Canadá', N'The Weeknd Essentials', N'Coleccion', N'Can''t Feel My Face', 213),
(N'The Weeknd', N'Canadá', N'The Weeknd Essentials', N'Coleccion', N'One of the Girls', 244),
(N'Taylor Swift', N'Estados Unidos', N'Taylor Swift Essentials', N'Coleccion', N'Cruel Summer', 178),
(N'Taylor Swift', N'Estados Unidos', N'Taylor Swift Essentials', N'Coleccion', N'Blank Space', 231),
(N'Taylor Swift', N'Estados Unidos', N'Taylor Swift Essentials', N'Coleccion', N'Anti-Hero', 200),
(N'Taylor Swift', N'Estados Unidos', N'Taylor Swift Essentials', N'Coleccion', N'Shake It Off', 219),
(N'Taylor Swift', N'Estados Unidos', N'Taylor Swift Essentials', N'Coleccion', N'Fortnight', 228),
(N'Billie Eilish', N'Estados Unidos', N'Billie Eilish Essentials', N'Coleccion', N'bad guy', 194),
(N'Billie Eilish', N'Estados Unidos', N'Billie Eilish Essentials', N'Coleccion', N'BIRDS OF A FEATHER', 210),
(N'Billie Eilish', N'Estados Unidos', N'Billie Eilish Essentials', N'Coleccion', N'ocean eyes', 200),
(N'Billie Eilish', N'Estados Unidos', N'Billie Eilish Essentials', N'Coleccion', N'when the party''s over', 196),
(N'Billie Eilish', N'Estados Unidos', N'Billie Eilish Essentials', N'Coleccion', N'lovely', 200),
(N'Olivia Rodrigo', N'Estados Unidos', N'Olivia Rodrigo Essentials', N'Coleccion', N'drivers license', 242),
(N'Olivia Rodrigo', N'Estados Unidos', N'Olivia Rodrigo Essentials', N'Coleccion', N'good 4 u', 178),
(N'Olivia Rodrigo', N'Estados Unidos', N'Olivia Rodrigo Essentials', N'Coleccion', N'vampire', 219),
(N'Olivia Rodrigo', N'Estados Unidos', N'Olivia Rodrigo Essentials', N'Coleccion', N'deja vu', 215),
(N'Olivia Rodrigo', N'Estados Unidos', N'Olivia Rodrigo Essentials', N'Coleccion', N'traitor', 229),
(N'SZA', N'Estados Unidos', N'SZA Essentials', N'Coleccion', N'Kill Bill', 153),
(N'SZA', N'Estados Unidos', N'SZA Essentials', N'Coleccion', N'Snooze', 201),
(N'SZA', N'Estados Unidos', N'SZA Essentials', N'Coleccion', N'Good Days', 279),
(N'SZA', N'Estados Unidos', N'SZA Essentials', N'Coleccion', N'Nobody Gets Me', 180),
(N'SZA', N'Estados Unidos', N'SZA Essentials', N'Coleccion', N'Broken Clocks', 231),
(N'Dua Lipa', N'Reino Unido', N'Dua Lipa Essentials', N'Coleccion', N'Levitating', 203),
(N'Dua Lipa', N'Reino Unido', N'Dua Lipa Essentials', N'Coleccion', N'Don''t Start Now', 183),
(N'Dua Lipa', N'Reino Unido', N'Dua Lipa Essentials', N'Coleccion', N'New Rules', 209),
(N'Dua Lipa', N'Reino Unido', N'Dua Lipa Essentials', N'Coleccion', N'Houdini', 185),
(N'Dua Lipa', N'Reino Unido', N'Dua Lipa Essentials', N'Coleccion', N'Training Season', 209),
(N'Ariana Grande', N'Estados Unidos', N'Ariana Grande Essentials', N'Coleccion', N'7 rings', 178),
(N'Ariana Grande', N'Estados Unidos', N'Ariana Grande Essentials', N'Coleccion', N'thank u, next', 207),
(N'Ariana Grande', N'Estados Unidos', N'Ariana Grande Essentials', N'Coleccion', N'positions', 172),
(N'Ariana Grande', N'Estados Unidos', N'Ariana Grande Essentials', N'Coleccion', N'we can''t be friends', 228),
(N'Ariana Grande', N'Estados Unidos', N'Ariana Grande Essentials', N'Coleccion', N'Into You', 244),
(N'Harry Styles', N'Reino Unido', N'Harry Styles Essentials', N'Coleccion', N'As It Was', 167),
(N'Harry Styles', N'Reino Unido', N'Harry Styles Essentials', N'Coleccion', N'Watermelon Sugar', 174),
(N'Harry Styles', N'Reino Unido', N'Harry Styles Essentials', N'Coleccion', N'Sign of the Times', 340),
(N'Harry Styles', N'Reino Unido', N'Harry Styles Essentials', N'Coleccion', N'Adore You', 207),
(N'Harry Styles', N'Reino Unido', N'Harry Styles Essentials', N'Coleccion', N'Late Night Talking', 178),
(N'Ed Sheeran', N'Reino Unido', N'Ed Sheeran Essentials', N'Coleccion', N'Shape of You', 234),
(N'Ed Sheeran', N'Reino Unido', N'Ed Sheeran Essentials', N'Coleccion', N'Perfect', 263),
(N'Ed Sheeran', N'Reino Unido', N'Ed Sheeran Essentials', N'Coleccion', N'Photograph', 258),
(N'Ed Sheeran', N'Reino Unido', N'Ed Sheeran Essentials', N'Coleccion', N'Bad Habits', 231),
(N'Ed Sheeran', N'Reino Unido', N'Ed Sheeran Essentials', N'Coleccion', N'Castle on the Hill', 261),
(N'Miley Cyrus', N'Estados Unidos', N'Miley Cyrus Essentials', N'Coleccion', N'Flowers', 200),
(N'Miley Cyrus', N'Estados Unidos', N'Miley Cyrus Essentials', N'Coleccion', N'Wrecking Ball', 221),
(N'Miley Cyrus', N'Estados Unidos', N'Miley Cyrus Essentials', N'Coleccion', N'Party in the U.S.A.', 202),
(N'Miley Cyrus', N'Estados Unidos', N'Miley Cyrus Essentials', N'Coleccion', N'Midnight Sky', 223),
(N'Miley Cyrus', N'Estados Unidos', N'Miley Cyrus Essentials', N'Coleccion', N'Used To Be Young', 191),
(N'Sabrina Carpenter', N'Estados Unidos', N'Sabrina Carpenter Essentials', N'Coleccion', N'Espresso', 175),
(N'Sabrina Carpenter', N'Estados Unidos', N'Sabrina Carpenter Essentials', N'Coleccion', N'Please Please Please', 186),
(N'Sabrina Carpenter', N'Estados Unidos', N'Sabrina Carpenter Essentials', N'Coleccion', N'Taste', 157),
(N'Sabrina Carpenter', N'Estados Unidos', N'Sabrina Carpenter Essentials', N'Coleccion', N'Nonsense', 163),
(N'Sabrina Carpenter', N'Estados Unidos', N'Sabrina Carpenter Essentials', N'Coleccion', N'Feather', 185),
(N'Morgan Wallen', N'Estados Unidos', N'Country Pop Essentials', N'Coleccion', N'Last Night', 163),
(N'Morgan Wallen', N'Estados Unidos', N'Country Pop Essentials', N'Coleccion', N'You Proof', 157),
(N'Morgan Wallen', N'Estados Unidos', N'Country Pop Essentials', N'Coleccion', N'Wasted On You', 178),
(N'Morgan Wallen', N'Estados Unidos', N'Country Pop Essentials', N'Coleccion', N'Thinkin'' Bout Me', 177),
(N'Morgan Wallen', N'Estados Unidos', N'Country Pop Essentials', N'Coleccion', N'Whiskey Glasses', 234),
(N'Karol G', N'Colombia', N'Karol G Essentials', N'Coleccion', N'TQG', 199),
(N'Karol G', N'Colombia', N'Karol G Essentials', N'Coleccion', N'Provenza', 210),
(N'Karol G', N'Colombia', N'Karol G Essentials', N'Coleccion', N'Mañana Será Bonito', 193),
(N'Karol G', N'Colombia', N'Karol G Essentials', N'Coleccion', N'Si Antes Te Hubiera Conocido', 195),
(N'Karol G', N'Colombia', N'Karol G Essentials', N'Coleccion', N'Mi Ex Tenía Razón', 154),
(N'Feid', N'Colombia', N'Feid Essentials', N'Coleccion', N'Luna', 196),
(N'Feid', N'Colombia', N'Feid Essentials', N'Coleccion', N'Feliz Cumpleaños Ferxxo', 155),
(N'Feid', N'Colombia', N'Feid Essentials', N'Coleccion', N'Classy 101', 195),
(N'Feid', N'Colombia', N'Feid Essentials', N'Coleccion', N'Normal', 172),
(N'Feid', N'Colombia', N'Feid Essentials', N'Coleccion', N'Chorrito Pa Las Animas', 168),
(N'J Balvin', N'Colombia', N'J Balvin Essentials', N'Coleccion', N'Mi Gente', 189),
(N'J Balvin', N'Colombia', N'J Balvin Essentials', N'Coleccion', N'Ginza', 171),
(N'J Balvin', N'Colombia', N'J Balvin Essentials', N'Coleccion', N'Rojo', 150),
(N'J Balvin', N'Colombia', N'J Balvin Essentials', N'Coleccion', N'Qué Más Pues?', 217),
(N'J Balvin', N'Colombia', N'J Balvin Essentials', N'Coleccion', N'Ay Vamos', 226),
(N'Maluma', N'Colombia', N'Maluma Essentials', N'Coleccion', N'Hawái', 199),
(N'Maluma', N'Colombia', N'Maluma Essentials', N'Coleccion', N'Felices los 4', 229),
(N'Maluma', N'Colombia', N'Maluma Essentials', N'Coleccion', N'Borro Cassette', 207),
(N'Maluma', N'Colombia', N'Maluma Essentials', N'Coleccion', N'Sobrio', 201),
(N'Maluma', N'Colombia', N'Maluma Essentials', N'Coleccion', N'Corazón', 184),
(N'Peso Pluma', N'México', N'Peso Pluma Essentials', N'Coleccion', N'Lady Gaga', 212),
(N'Peso Pluma', N'México', N'Peso Pluma Essentials', N'Coleccion', N'Ella Baila Sola', 165),
(N'Peso Pluma', N'México', N'Peso Pluma Essentials', N'Coleccion', N'PRC', 184),
(N'Peso Pluma', N'México', N'Peso Pluma Essentials', N'Coleccion', N'La Bebé', 234),
(N'Peso Pluma', N'México', N'Peso Pluma Essentials', N'Coleccion', N'La People', 153),
(N'Junior H', N'México', N'Junior H Essentials', N'Coleccion', N'Y Lloro', 181),
(N'Junior H', N'México', N'Junior H Essentials', N'Coleccion', N'Fin de Semana', 224),
(N'Junior H', N'México', N'Junior H Essentials', N'Coleccion', N'El Azul', 188),
(N'Junior H', N'México', N'Junior H Essentials', N'Coleccion', N'Extssy Model', 156),
(N'Junior H', N'México', N'Junior H Essentials', N'Coleccion', N'Las 3 Torres', 198),
(N'Natanael Cano', N'México', N'Natanael Cano Essentials', N'Coleccion', N'Amor Tumbado', 211),
(N'Natanael Cano', N'México', N'Natanael Cano Essentials', N'Coleccion', N'Madonna', 187),
(N'Natanael Cano', N'México', N'Natanael Cano Essentials', N'Coleccion', N'Pacas de Billetes', 205),
(N'Natanael Cano', N'México', N'Natanael Cano Essentials', N'Coleccion', N'PRC', 184),
(N'Natanael Cano', N'México', N'Natanael Cano Essentials', N'Coleccion', N'AMG', 175),
(N'Imagine Dragons', N'Estados Unidos', N'Rock Pop Essentials', N'Coleccion', N'Believer', 204),
(N'Imagine Dragons', N'Estados Unidos', N'Rock Pop Essentials', N'Coleccion', N'Radioactive', 186),
(N'Imagine Dragons', N'Estados Unidos', N'Rock Pop Essentials', N'Coleccion', N'Demons', 178),
(N'Imagine Dragons', N'Estados Unidos', N'Rock Pop Essentials', N'Coleccion', N'Thunder', 187),
(N'Imagine Dragons', N'Estados Unidos', N'Rock Pop Essentials', N'Coleccion', N'Whatever It Takes', 201),
(N'Coldplay', N'Reino Unido', N'Coldplay Essentials', N'Coleccion', N'Yellow', 267),
(N'Coldplay', N'Reino Unido', N'Coldplay Essentials', N'Coleccion', N'Viva La Vida', 242),
(N'Coldplay', N'Reino Unido', N'Coldplay Essentials', N'Coleccion', N'Something Just Like This', 247),
(N'Coldplay', N'Reino Unido', N'Coldplay Essentials', N'Coleccion', N'A Sky Full of Stars', 268),
(N'Coldplay', N'Reino Unido', N'Coldplay Essentials', N'Coleccion', N'Fix You', 295),
(N'Linkin Park', N'Estados Unidos', N'Alternative Rock Essentials', N'Coleccion', N'In the End', 216),
(N'Linkin Park', N'Estados Unidos', N'Alternative Rock Essentials', N'Coleccion', N'Numb', 187),
(N'Linkin Park', N'Estados Unidos', N'Alternative Rock Essentials', N'Coleccion', N'What I''ve Done', 205),
(N'Linkin Park', N'Estados Unidos', N'Alternative Rock Essentials', N'Coleccion', N'Faint', 163),
(N'Linkin Park', N'Estados Unidos', N'Alternative Rock Essentials', N'Coleccion', N'One Step Closer', 157),
(N'Arctic Monkeys', N'Reino Unido', N'Indie Rock Essentials', N'Coleccion', N'Do I Wanna Know?', 272),
(N'Arctic Monkeys', N'Reino Unido', N'Indie Rock Essentials', N'Coleccion', N'505', 253),
(N'Arctic Monkeys', N'Reino Unido', N'Indie Rock Essentials', N'Coleccion', N'R U Mine?', 201),
(N'Arctic Monkeys', N'Reino Unido', N'Indie Rock Essentials', N'Coleccion', N'I Wanna Be Yours', 184),
(N'Arctic Monkeys', N'Reino Unido', N'Indie Rock Essentials', N'Coleccion', N'Fluorescent Adolescent', 183),
(N'Tame Impala', N'Australia', N'Psychedelic Pop Essentials', N'Coleccion', N'The Less I Know The Better', 216),
(N'Tame Impala', N'Australia', N'Psychedelic Pop Essentials', N'Coleccion', N'Let It Happen', 467),
(N'Tame Impala', N'Australia', N'Psychedelic Pop Essentials', N'Coleccion', N'Borderline', 237),
(N'Tame Impala', N'Australia', N'Psychedelic Pop Essentials', N'Coleccion', N'Feels Like We Only Go Backwards', 193),
(N'Tame Impala', N'Australia', N'Psychedelic Pop Essentials', N'Coleccion', N'New Person, Same Old Mistakes', 363),
(N'Metallica', N'Estados Unidos', N'Metal Essentials', N'Coleccion', N'Enter Sandman', 332),
(N'Metallica', N'Estados Unidos', N'Metal Essentials', N'Coleccion', N'Nothing Else Matters', 388),
(N'Metallica', N'Estados Unidos', N'Metal Essentials', N'Coleccion', N'Master of Puppets', 515),
(N'Metallica', N'Estados Unidos', N'Metal Essentials', N'Coleccion', N'One', 447),
(N'Metallica', N'Estados Unidos', N'Metal Essentials', N'Coleccion', N'Sad But True', 324),
(N'Queen', N'Reino Unido', N'Classic Rock Essentials', N'Coleccion', N'Bohemian Rhapsody', 354),
(N'Queen', N'Reino Unido', N'Classic Rock Essentials', N'Coleccion', N'Don''t Stop Me Now', 209),
(N'Queen', N'Reino Unido', N'Classic Rock Essentials', N'Coleccion', N'Another One Bites the Dust', 215),
(N'Queen', N'Reino Unido', N'Classic Rock Essentials', N'Coleccion', N'We Will Rock You', 122),
(N'Queen', N'Reino Unido', N'Classic Rock Essentials', N'Coleccion', N'Radio Ga Ga', 343),
(N'Daft Punk', N'Francia', N'Electronic Essentials', N'Coleccion', N'Get Lucky', 369),
(N'Daft Punk', N'Francia', N'Electronic Essentials', N'Coleccion', N'One More Time', 320),
(N'Daft Punk', N'Francia', N'Electronic Essentials', N'Coleccion', N'Harder Better Faster Stronger', 224),
(N'Daft Punk', N'Francia', N'Electronic Essentials', N'Coleccion', N'Around the World', 429),
(N'Daft Punk', N'Francia', N'Electronic Essentials', N'Coleccion', N'Instant Crush', 337),
(N'Calvin Harris', N'Reino Unido', N'EDM Essentials', N'Coleccion', N'Summer', 223),
(N'Calvin Harris', N'Reino Unido', N'EDM Essentials', N'Coleccion', N'Feel So Close', 206),
(N'Calvin Harris', N'Reino Unido', N'EDM Essentials', N'Coleccion', N'One Kiss', 214),
(N'Calvin Harris', N'Reino Unido', N'EDM Essentials', N'Coleccion', N'This Is What You Came For', 222),
(N'Calvin Harris', N'Reino Unido', N'EDM Essentials', N'Coleccion', N'How Deep Is Your Love', 212),
(N'Martin Garrix', N'Países Bajos', N'Festival EDM Essentials', N'Coleccion', N'Animals', 303),
(N'Martin Garrix', N'Países Bajos', N'Festival EDM Essentials', N'Coleccion', N'Scared to Be Lonely', 221),
(N'Martin Garrix', N'Países Bajos', N'Festival EDM Essentials', N'Coleccion', N'In the Name of Love', 196),
(N'Martin Garrix', N'Países Bajos', N'Festival EDM Essentials', N'Coleccion', N'Tremor', 294),
(N'Martin Garrix', N'Países Bajos', N'Festival EDM Essentials', N'Coleccion', N'High on Life', 230),
(N'Avicii', N'Suecia', N'Avicii Essentials', N'Coleccion', N'Wake Me Up', 247),
(N'Avicii', N'Suecia', N'Avicii Essentials', N'Coleccion', N'The Nights', 176),
(N'Avicii', N'Suecia', N'Avicii Essentials', N'Coleccion', N'Levels', 199),
(N'Avicii', N'Suecia', N'Avicii Essentials', N'Coleccion', N'Hey Brother', 254),
(N'Avicii', N'Suecia', N'Avicii Essentials', N'Coleccion', N'Waiting For Love', 230),
(N'Beyoncé', N'Estados Unidos', N'Beyoncé Essentials', N'Coleccion', N'TEXAS HOLD ''EM', 233),
(N'Beyoncé', N'Estados Unidos', N'Beyoncé Essentials', N'Coleccion', N'CUFF IT', 225),
(N'Beyoncé', N'Estados Unidos', N'Beyoncé Essentials', N'Coleccion', N'Crazy In Love', 236),
(N'Beyoncé', N'Estados Unidos', N'Beyoncé Essentials', N'Coleccion', N'HALO', 261),
(N'Beyoncé', N'Estados Unidos', N'Beyoncé Essentials', N'Coleccion', N'BREAK MY SOUL', 278),
(N'Rihanna', N'Barbados', N'Rihanna Essentials', N'Coleccion', N'Umbrella', 275),
(N'Rihanna', N'Barbados', N'Rihanna Essentials', N'Coleccion', N'Diamonds', 225),
(N'Rihanna', N'Barbados', N'Rihanna Essentials', N'Coleccion', N'Work', 219),
(N'Rihanna', N'Barbados', N'Rihanna Essentials', N'Coleccion', N'We Found Love', 215),
(N'Rihanna', N'Barbados', N'Rihanna Essentials', N'Coleccion', N'Only Girl', 235),
(N'Bruno Mars', N'Estados Unidos', N'Bruno Mars Essentials', N'Coleccion', N'Uptown Funk', 270),
(N'Bruno Mars', N'Estados Unidos', N'Bruno Mars Essentials', N'Coleccion', N'Locked out of Heaven', 233),
(N'Bruno Mars', N'Estados Unidos', N'Bruno Mars Essentials', N'Coleccion', N'Just the Way You Are', 221),
(N'Bruno Mars', N'Estados Unidos', N'Bruno Mars Essentials', N'Coleccion', N'That''s What I Like', 206),
(N'Bruno Mars', N'Estados Unidos', N'Bruno Mars Essentials', N'Coleccion', N'24K Magic', 226),
(N'Kali Uchis', N'Colombia', N'R&B Latino Essentials', N'Coleccion', N'telepatía', 160),
(N'Kali Uchis', N'Colombia', N'R&B Latino Essentials', N'Coleccion', N'Moonlight', 187),
(N'Kali Uchis', N'Colombia', N'R&B Latino Essentials', N'Coleccion', N'After the Storm', 207),
(N'Kali Uchis', N'Colombia', N'R&B Latino Essentials', N'Coleccion', N'Melting', 208),
(N'Kali Uchis', N'Colombia', N'R&B Latino Essentials', N'Coleccion', N'Igual Que Un Ángel', 260),
(N'Rosalía', N'España', N'Rosalía Essentials', N'Coleccion', N'DESPECHÁ', 157),
(N'Rosalía', N'España', N'Rosalía Essentials', N'Coleccion', N'LA FAMA', 188),
(N'Rosalía', N'España', N'Rosalía Essentials', N'Coleccion', N'MALAMENTE', 150),
(N'Rosalía', N'España', N'Rosalía Essentials', N'Coleccion', N'SAOKO', 137),
(N'Rosalía', N'España', N'Rosalía Essentials', N'Coleccion', N'BESO', 194),
(N'Shakira', N'Colombia', N'Shakira Essentials', N'Coleccion', N'Hips Don''t Lie', 218),
(N'Shakira', N'Colombia', N'Shakira Essentials', N'Coleccion', N'Waka Waka', 202),
(N'Shakira', N'Colombia', N'Shakira Essentials', N'Coleccion', N'Monotonía', 158),
(N'Shakira', N'Colombia', N'Shakira Essentials', N'Coleccion', N'BZRP Music Sessions Vol. 53', 218),
(N'Shakira', N'Colombia', N'Shakira Essentials', N'Coleccion', N'Whenever, Wherever', 196),
(N'Manuel Turizo', N'Colombia', N'Pop Urbano Essentials', N'Coleccion', N'La Bachata', 162),
(N'Manuel Turizo', N'Colombia', N'Pop Urbano Essentials', N'Coleccion', N'Una Lady Como Tú', 213),
(N'Manuel Turizo', N'Colombia', N'Pop Urbano Essentials', N'Coleccion', N'El Merengue', 189),
(N'Manuel Turizo', N'Colombia', N'Pop Urbano Essentials', N'Coleccion', N'Vagabundo', 215),
(N'Manuel Turizo', N'Colombia', N'Pop Urbano Essentials', N'Coleccion', N'Déjala Que Vuelva', 215),
(N'Ozuna', N'Puerto Rico', N'Ozuna Essentials', N'Coleccion', N'Se Preparó', 188),
(N'Ozuna', N'Puerto Rico', N'Ozuna Essentials', N'Coleccion', N'Criminal', 235),
(N'Ozuna', N'Puerto Rico', N'Ozuna Essentials', N'Coleccion', N'Baila Baila Baila', 158),
(N'Ozuna', N'Puerto Rico', N'Ozuna Essentials', N'Coleccion', N'Taki Taki', 212),
(N'Ozuna', N'Puerto Rico', N'Ozuna Essentials', N'Coleccion', N'Caramelo', 218),
(N'Anuel AA', N'Puerto Rico', N'Anuel AA Essentials', N'Coleccion', N'Sola', 214),
(N'Anuel AA', N'Puerto Rico', N'Anuel AA Essentials', N'Coleccion', N'Secreto', 258),
(N'Anuel AA', N'Puerto Rico', N'Anuel AA Essentials', N'Coleccion', N'China', 302),
(N'Anuel AA', N'Puerto Rico', N'Anuel AA Essentials', N'Coleccion', N'Me Gusta', 189),
(N'Anuel AA', N'Puerto Rico', N'Anuel AA Essentials', N'Coleccion', N'Adicto', 270),
(N'Daddy Yankee', N'Puerto Rico', N'Daddy Yankee Essentials', N'Coleccion', N'Gasolina', 193),
(N'Daddy Yankee', N'Puerto Rico', N'Daddy Yankee Essentials', N'Coleccion', N'Con Calma', 193),
(N'Daddy Yankee', N'Puerto Rico', N'Daddy Yankee Essentials', N'Coleccion', N'Limbo', 224),
(N'Daddy Yankee', N'Puerto Rico', N'Daddy Yankee Essentials', N'Coleccion', N'Rompe', 190),
(N'Daddy Yankee', N'Puerto Rico', N'Daddy Yankee Essentials', N'Coleccion', N'La Despedida', 202),
(N'Wisin & Yandel', N'Puerto Rico', N'Reggaeton Clásico Essentials', N'Coleccion', N'Rakata', 188),
(N'Wisin & Yandel', N'Puerto Rico', N'Reggaeton Clásico Essentials', N'Coleccion', N'Abusadora', 208),
(N'Wisin & Yandel', N'Puerto Rico', N'Reggaeton Clásico Essentials', N'Coleccion', N'Pam Pam', 214),
(N'Wisin & Yandel', N'Puerto Rico', N'Reggaeton Clásico Essentials', N'Coleccion', N'Ahora Es', 205),
(N'Wisin & Yandel', N'Puerto Rico', N'Reggaeton Clásico Essentials', N'Coleccion', N'Sexy Movimiento', 202),
(N'Myke Towers', N'Puerto Rico', N'Myke Towers Essentials', N'Coleccion', N'LALA', 197),
(N'Myke Towers', N'Puerto Rico', N'Myke Towers Essentials', N'Coleccion', N'Diosa', 214),
(N'Myke Towers', N'Puerto Rico', N'Myke Towers Essentials', N'Coleccion', N'La Curiosidad', 220),
(N'Myke Towers', N'Puerto Rico', N'Myke Towers Essentials', N'Coleccion', N'Girl', 212),
(N'Myke Towers', N'Puerto Rico', N'Myke Towers Essentials', N'Coleccion', N'Experimento', 201),
(N'Eladio Carrión', N'Puerto Rico', N'Eladio Carrión Essentials', N'Coleccion', N'Coco Chanel', 208),
(N'Eladio Carrión', N'Puerto Rico', N'Eladio Carrión Essentials', N'Coleccion', N'Kemba Walker', 206),
(N'Eladio Carrión', N'Puerto Rico', N'Eladio Carrión Essentials', N'Coleccion', N'Mbappe', 196),
(N'Eladio Carrión', N'Puerto Rico', N'Eladio Carrión Essentials', N'Coleccion', N'Hola Cómo Vas', 192),
(N'Eladio Carrión', N'Puerto Rico', N'Eladio Carrión Essentials', N'Coleccion', N'No Te Deseo el Mal', 202),
(N'Quevedo', N'España', N'Quevedo Essentials', N'Coleccion', N'BZRP Music Sessions Vol. 52', 198),
(N'Quevedo', N'España', N'Quevedo Essentials', N'Coleccion', N'Vista al Mar', 183),
(N'Quevedo', N'España', N'Quevedo Essentials', N'Coleccion', N'Columbia', 186),
(N'Quevedo', N'España', N'Quevedo Essentials', N'Coleccion', N'Playa del Inglés', 238),
(N'Quevedo', N'España', N'Quevedo Essentials', N'Coleccion', N'Buenas', 181),
(N'Central Cee', N'Reino Unido', N'UK Rap Essentials', N'Coleccion', N'Dojo', 105),
(N'Central Cee', N'Reino Unido', N'UK Rap Essentials', N'Coleccion', N'Sprinter', 229),
(N'Central Cee', N'Reino Unido', N'UK Rap Essentials', N'Coleccion', N'Loading', 173),
(N'Central Cee', N'Reino Unido', N'UK Rap Essentials', N'Coleccion', N'Let Go', 174),
(N'Central Cee', N'Reino Unido', N'UK Rap Essentials', N'Coleccion', N'Band4Band', 140),
(N'21 Savage', N'Estados Unidos', N'21 Savage Essentials', N'Coleccion', N'Bank Account', 220),
(N'21 Savage', N'Estados Unidos', N'21 Savage Essentials', N'Coleccion', N'a lot', 288),
(N'21 Savage', N'Estados Unidos', N'21 Savage Essentials', N'Coleccion', N'red rum', 270),
(N'21 Savage', N'Estados Unidos', N'21 Savage Essentials', N'Coleccion', N'Rich Flex', 239),
(N'21 Savage', N'Estados Unidos', N'21 Savage Essentials', N'Coleccion', N'No Heart', 236),
(N'Future', N'Estados Unidos', N'Future Essentials', N'Coleccion', N'Mask Off', 204),
(N'Future', N'Estados Unidos', N'Future Essentials', N'Coleccion', N'Life Is Good', 237),
(N'Future', N'Estados Unidos', N'Future Essentials', N'Coleccion', N'WAIT FOR U', 189),
(N'Future', N'Estados Unidos', N'Future Essentials', N'Coleccion', N'Like That', 267),
(N'Future', N'Estados Unidos', N'Future Essentials', N'Coleccion', N'March Madness', 262);

INSERT INTO Catalogo.Artista (nombreArtistico, biografia, pais, estadoArtista, idDiscografica)
SELECT DISTINCT
    p.artista,
    'Artista agregado al catálogo global de StreamFlow.',
    p.pais,
    'Activo',
    @idDiscograficaPopular
FROM @Popular p
WHERE NOT EXISTS (
    SELECT 1
    FROM Catalogo.Artista a
    WHERE a.nombreArtistico = p.artista
);

UPDATE a
SET idDiscografica = @idDiscograficaPopular
FROM Catalogo.Artista a
INNER JOIN (
    SELECT DISTINCT artista
    FROM @Popular
) p
    ON p.artista = a.nombreArtistico
WHERE a.idDiscografica IS NULL;

INSERT INTO Catalogo.Album (idArtista, titulo, fechaLanzamiento, tipo)
SELECT DISTINCT
    a.idArtista,
    p.album,
    '2025-01-01',
    'Album'
FROM @Popular p
INNER JOIN Catalogo.Artista a
    ON a.nombreArtistico = p.artista
WHERE NOT EXISTS (
    SELECT 1
    FROM Catalogo.Album al
    WHERE al.idArtista = a.idArtista
      AND al.titulo = p.album
);

INSERT INTO Catalogo.Cancion (idAlbum, titulo, duracionSeg, estadoCancion)
SELECT
    al.idAlbum,
    p.titulo,
    p.duracionSeg,
    'Activo'
FROM @Popular p
INNER JOIN Catalogo.Artista a
    ON a.nombreArtistico = p.artista
INNER JOIN Catalogo.Album al
    ON al.idArtista = a.idArtista
   AND al.titulo = p.album
WHERE NOT EXISTS (
    SELECT 1
    FROM Catalogo.Cancion c
    WHERE c.idAlbum = al.idAlbum
      AND c.titulo = p.titulo
);
GO
